preload=/home/kai/.dotfiles/wallpapers/Heusden_half_shaded.JPG
preload=/home/kai/.dotfiles/wallpapers/Heusden_village.JPG
preload=/home/kai/.dotfiles/wallpapers/Rice_fields_bolt.JPG
preload=/home/kai/.dotfiles/wallpapers/Rice_fields_above.JPG
preload=/home/kai/.dotfiles/wallpapers/Castle_slangeburg_snow.JPG
preload=/home/kai/.dotfiles/wallpapers/snowy_forest.JPG
preload=/home/kai/.dotfiles/wallpapers/snowy_forest.JPG
preload=/home/kai/.dotfiles/wallpapers/Turtle_tiger_above.JPG

#====================
#=====wallpapers=====
#====================

#Heusden

#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Heusden_half_shaded.JPG
#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Heusden_village.JPG

#Rijst velden
#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Rice_fields_bolt.JPG
#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Rice_fields_above.JPG

#Kasteel slangenburg
#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Castle_slangeburg_snow.JPG
wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/snowy_forest.JPG

#Tiger & Turtle
#wallpaper=eDP-1, /home/kai/.dotfiles/wallpapers/Turtle_tiger_above.JPG
