$accent = rgb(129, 200, 190)
$accentAlpha = rgb(140, 170, 238)
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = false
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprpaper_wallpapers/snowy_forest.JPG
    blur_passes = 3
    color = rgb(48, 52, 70)
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = rgb(198, 208, 245)
    font_size = 90
    font_family = $font
    position = 0, 370
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = rgb(198, 208, 245)
    font_size = 25
    font_family = $font
    position = 0, 270
    halign = center
    valign = center
}

# USER AVATAR
image {
    monitor =
    path = ~/.config/hypr/avatar.jpg
    size = 130
    border_color = $accent
    position = 0, 125
    halign = center
    valign = center
}

# USERNAME
label {
    text = Kai Schakel
    color = $accent
    font_size = 25
    font_family = $font
    position = 0, 35
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 350, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgb(65, 69, 89)
    font_color = rgb(198, 208, 245)
    fade_on_empty = false
    placeholder_text = Please enter PIN.
    foreground=$USER
    hide_input = false
    check_color = $accent
    fail_color = rgb(231, 130, 132)
    fail_text = $ATTEMPTS
    capslock_color = rgb(229, 200, 144)
    position = 0, -80
    halign = center
    valign = center
}
